entities:
  product:
    table: 'Products'
    key: 'ProductId'
    displayName: 'Product'
    softDelete: false
    paging:
      pageSize: 20
      mode: numbered
    layout:
      forms:
        columns: 2
        order: ['ProductName', 'SupplierId', 'CategoryId', 'UnitPrice', 'UnitsInStock', 'ReorderLevel', 'Discontinued']
      filters:
        columns: 4
        order: []
    columns:
      ProductId: { type: int, identity: true, label: 'Product Id', sortable: true }
      ProductName: { type: string, required: true, label: 'Product Name', searchable: true, sortable: true }
      SupplierId: { type: int, required: true, label: 'Supplier Id', sortable: true }
      CategoryId: { type: int, required: true, label: 'Category Id', sortable: true }
      UnitPrice: { type: decimal, required: true, label: 'Unit Price', sortable: true }
      UnitsInStock: { type: int, label: 'Units In Stock', sortable: true }
      ReorderLevel: { type: int, label: 'Reorder Level', sortable: true }
      Discontinued: { type: int, label: 'Discontinued', sortable: true }
    forms:
      ProductName: { type: string, required: true, label: 'Product Name', editable: true }
      SupplierId:
        type: int
        required: true
        label: 'Supplier Id'
        editable: true
        foreignKey:
          entity: supplier
          displayColumn: 'CompanyName'
      CategoryId:
        type: int
        required: true
        label: 'Category Id'
        editable: true
        foreignKey:
          entity: category
          displayColumn: 'CategoryName'
      UnitPrice: { type: decimal, required: true, label: 'Unit Price', editable: true }
      UnitsInStock: { type: int, label: 'Units In Stock', editable: true }
      ReorderLevel: { type: int, label: 'Reorder Level', editable: true }
      Discontinued: { type: int, label: 'Discontinued', editable: true }
    filters: {}
    links: {}
