entities:
  sso_principalconfig:
    table: sso_principalconfig
    key: sso_principalconfig_id
    displayName: SSO_PRINCIPALCONFIG
    columns:
      ad_client_id: {type: decimal}
      ad_org_id: {type: decimal}
      created: {type: string}
      createdby: {type: decimal}
      isactive: {type: string}
      name: {type: string}
      sso_applicationclientid: {type: string}
      sso_applicationlogouturl: {type: string}
      sso_applicationredirecturis: {type: string}
      sso_applicationsecretkey: {type: string}
      sso_authorizationtenantid: {type: string}
      sso_principalconfig_id: {type: decimal, identity: true}
      sso_principalconfig_uu: {type: string}
      updated: {type: string}
      updatedby: {type: decimal}
      isdefault: {type: string}
      sso_provider: {type: string}
      sso_applicationdiscoveryuri: {type: string}
      sso_idempmonitorredirecturis: {type: string}
      sso_osgiredirecturis: {type: string}
      sso_loginbuttonimage_id: {type: decimal}
