entities:
  invoice:
    table: Invoice
    key: InvoiceId
    displayName: Invoice
    softDelete: false
    paging:
      pageSize: 10
      mode: numbered
      enableCount: false
    layout:
      forms:
        columns: 2
        order:
        - CustomerId
        - InvoiceDate
        - BillingAddress
        - BillingCity
        - BillingState
        - BillingCountry
        - BillingPostalCode
        - Total
      filters:
        columns: 3
        order:
        - CustomerId
        - BillingCountry
        - InvoiceDate
        - Total
    joins:
    - type: left
      table: Customer
      alias: c
      true: Invoice.CustomerId = c.CustomerId
    columns:
      InvoiceId:
        type: int
        identity: true
        label: ID
        searchable: false
        sortable: true
        labelKey: config.entities.invoice.entities.invoice.columns.InvoiceId.label
      CustomerId:
        type: int
        label: Customer
        sortable: true
        labelKey: config.entities.invoice.entities.invoice.columns.CustomerId.label
      CustomerName:
        type: string
        identity: true
        label: Customer
        expression: c.LastName || ', ' || c.FirstName
        searchable: true
        sortable: true
        labelKey: config.entities.invoice.entities.invoice.columns.CustomerName.label
      InvoiceDate:
        type: date
        label: Invoice Date
        searchable: false
        sortable: true
        labelKey: config.entities.invoice.entities.invoice.columns.InvoiceDate.label
      BillingCountry:
        type: string
        label: Billing Country
        searchable: true
        sortable: true
        labelKey: config.entities.invoice.entities.invoice.columns.BillingCountry.label
      Total:
        type: decimal
        label: Total
        searchable: false
        sortable: true
        labelKey: config.entities.invoice.entities.invoice.columns.Total.label
      BillingAddress:
        type: textarea
        hidden: true
        label: Billing Address
        labelKey: config.entities.invoice.entities.invoice.columns.BillingAddress.label
      BillingCity:
        type: string
        hidden: true
        label: Billing City
        labelKey: config.entities.invoice.entities.invoice.columns.BillingCity.label
      BillingState:
        type: string
        hidden: true
        label: Billing State
        labelKey: config.entities.invoice.entities.invoice.columns.BillingState.label
      BillingPostalCode:
        type: string
        hidden: true
        label: Billing Postal Code
        labelKey: config.entities.invoice.entities.invoice.columns.BillingPostalCode.label
    forms:
      CustomerId:
        type: int
        label: Customer
        editable: true
        foreignKey:
          entity: customer
          displayColumn: LastName
        labelKey: config.entities.invoice.entities.invoice.forms.CustomerId.label
      InvoiceDate:
        type: date
        label: Invoice Date
        editable: true
        labelKey: config.entities.invoice.entities.invoice.forms.InvoiceDate.label
      BillingAddress:
        type: textarea
        label: Billing Address
        editable: true
        labelKey: config.entities.invoice.entities.invoice.forms.BillingAddress.label
      BillingCity:
        type: string
        label: Billing City
        editable: true
        labelKey: config.entities.invoice.entities.invoice.forms.BillingCity.label
      BillingState:
        type: string
        label: Billing State
        editable: true
        labelKey: config.entities.invoice.entities.invoice.forms.BillingState.label
      BillingCountry:
        type: string
        label: Billing Country
        editable: true
        labelKey: config.entities.invoice.entities.invoice.forms.BillingCountry.label
      BillingPostalCode:
        type: string
        label: Billing Postal Code
        editable: true
        labelKey: config.entities.invoice.entities.invoice.forms.BillingPostalCode.label
      Total:
        type: decimal
        label: Total
        editable: true
        labelKey: config.entities.invoice.entities.invoice.forms.Total.label
    filters:
      CustomerId:
        type: dropdown
        label: Customer
        expression: Invoice.CustomerId
        foreignKey:
          entity: customer
          displayColumn: LastName
        labelKey: config.entities.invoice.entities.invoice.filters.CustomerId.label
      BillingCountry:
        type: multi-select
        label: Billing Country
        options:
        - USA
        - Canada
        - Brazil
        - France
        - Germany
        labelKey: config.entities.invoice.entities.invoice.filters.BillingCountry.label
      InvoiceDate:
        type: date-range
        label: Invoice Date
        expression: Invoice.InvoiceDate
        labelKey: config.entities.invoice.entities.invoice.filters.InvoiceDate.label
      Total:
        type: range
        label: Total Range
        expression: Invoice.Total
        labelKey: config.entities.invoice.entities.invoice.filters.Total.label
    displayNameKey: config.entities.invoice.entities.invoice.displayName
