header:
  title: Tmp Mode Display
navigation:
  showDashboard: true
  entities: []
  items:
    - label: Home
      url: /tmp-mode-display
      icon: 🏠
    - label: Dashboard
      controller: Dashboard
      action: Index
      icon: 📊
